name: Build Android Kernel

on:
  push:
    branches:
      - master  # أو الفرع الذي تريد تفعيل الـ workflow عليه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. استنساخ مستودع الكود
      - name: Checkout kernel source
        uses: actions/checkout@v2

      # 2. استنساخ AnyKernel3
      - name: Checkout zipper
        uses: actions/checkout@v2
        with:
          repository: lemniskett/AnyKernel3
          path: zipper

      # 3. بناء النواة
      - name: Android kernel build
        uses: lemniskett/android-kernel-actions@master
        id: build
        env:
          NAME: Dark-Ages-Último
        with:
          arch: arm64
          compiler: gcc/10
          defconfig: kernel/arch/arm64/configs/vendor/y2q_chn_hkx_defconfig  # المسار الكامل لملف defconfig
          image: Image.gz-dtb

      # 4. نشر البناء
      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.build.outputs.outfile }}
          token: ${{ secrets.GITHUB_TOKEN }}  # استخدم الـ GitHub Token للمصادقة
