name: Build Android Kernel

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]  # Triggers on push to the "main" branch
  workflow_dispatch:      # Allows manual trigger from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies Ubuntu as the runner

    steps:
      # 1. Checkout the kernel source code
      - name: Checkout kernel source
        uses: actions/checkout@v2
        with:
          repository: your_username/your_kernel_repo  # Replace with your repository details

      # 2. Set up toolchain (download and install)
      - name: Set up toolchain
        run: |
          # Download toolchain from Android Git server or another source
          wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.tar.gz
          tar -xvf aarch64-linux-android-4.9.tar.gz
          export CROSS_COMPILE=$PWD/aarch64-linux-android-4.9/bin/aarch64-linux-android-
          export CLANG_TRIPLE=aarch64-linux-gnu-

      # 3. Checkout AnyKernel3 (for creating flashable zip files)
      - name: Checkout AnyKernel3
        uses: actions/checkout@v2
        with:
          repository: lemniskett/AnyKernel3
          path: zipper

      # 4. Build the Android kernel
      - name: Build Android kernel
        uses: lemniskett/android-kernel-actions@master
        id: build
        env:
          NAME: "Custom-Kernel"   # Set the release name for the kernel
        with:
          arch: arm64            # Specify the target architecture
          compiler: gcc/10       # Specify toolchain to use
          defconfig: vendor/y2q_chn_hkx_defconfig  # Use your device-specific defconfig
          image: Image.gz-dtb    # Output image name (e.g., Image.gz-dtb or Image-dtb)

      # 5. Release the build using GitHub Release
      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.build.outputs.outfile }}  # Path to the final build file
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for API access
