name: Build Android Kernel

on:
  push:
    branches:
      - master  # أو الفرع الذي تريد تفعيل الـ workflow عليه
    tags:
      - '*'  # لتفعيل الـ workflow عند دفع تاغ جديد

jobs:
  build:
    runs-on: ubuntu-24.04.1

    steps:
      # 1. استنساخ مستودع الكود
      - name: Checkout kernel source
        uses: actions/checkout@v2

      # 2. استنساخ AnyKernel3
      - name: Checkout zipper
        uses: actions/checkout@v2
        with:
          repository: lemniskett/AnyKernel3
          path: zipper

      # 3. بناء النواة
      - name: Android kernel build
        uses: lemniskett/android-kernel-actions@master
        id: build
        env:
          NAME: fahad-kernel  # اسم الإصدار
        with:
          arch: arm64  # تحديد المعمارية
          compiler: gcc/10  # اختيار الـ toolchain المستخدم (gcc/10)
          defconfig: kernel/arch/arm64/configs/vendor/y2q_chn_hkx_defconfig  # المسار الكامل لملف defconfig
          image: Image.gz-dtb  # تحديد نوع الصورة الناتجة

      # 4. نشر البناء
      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.build.outputs.outfile }}  # المسار إلى الملف الناتج
          token: ${{ secrets.GITHUB_TOKEN }}  # استخدام الـ GitHub Token للمصادقة
